### ISSUE TITLE
please tag release v0.7.0

### ISSUE THREAD

**Issue by jonassmedegaard** [Lokathor/safe_arch#109]
Newest release at crates.io is 0.7.0, which is not tagged in git.

Please tag the release, to ease checking source against released code.

**Comment by Lokathor** [comment]
That's very strange, `cargo-release` usually makes the tags I'm not sure why it didn't do one this time.

**Comment by Lokathor** [comment]
Well I couldn't figure out which commit was 0.7.0 exactly, so I just put out 0.7.1 since there's some prefetch functions that have been waiting to get out, and that has a tag.

**Comment by jonassmedegaard** [comment]
Thanks!

My interest, specifically (in case you are curious) is for streamlining future maintenance - I am in the process of packaging this (and wide, palette, and git-delta) for Debian: https://bugs.debian.org/1041314
