### ISSUE TITLE
Unsound usages of unsafe implementation from `i64` to `__m128i`

### ISSUE THREAD

**Issue by llooFlashooll** [Lokathor/safe_arch#116]
Hi, I am scanning the safe_arch in the latest version with my own static analyzer tool.

Unsafe conversion found at: src/runtime.rs#L506
``` rust
#[inline(always)]
#[allow(clippy::cast_ptr_alignment)]
#[cfg_attr(docsrs, doc(cfg(target_feature = "sse2")))]
pub fn store_i64_m128i_s(r: &mut i64, a: m128i) {
  unsafe { _mm_storel_epi64(r as *mut i64 as *mut __m128i, a.0) }
}
```

This unsound implementation would create a misalignment issues if the type size of `i64` is smaller than the type size of `__m128i`.

This would potentially cause [undefined behaviors](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in Rust. If we further manipulate the problematic converted types, it would potentially lead to different consequences such as access out-of-bound. I am reporting this issue for your attention.

**Comment by Lokathor** [comment]
That's not how the `_mm_storel_epi64` intrinsic works. It doesn't store the entire m128i, it only stores the lower 64 bits.
