### ISSUE TITLE
Fix all floating point docs about "ord" and "unord"

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/safe_arch#37]
It's not "ordinary" it's "ordered", as in "can be ordered" as in "not nan".

**Comment by Soveu** [comment]
`grep -ri 'ordinary'` does not find any occurrences of 'ordinary'

**Comment by Lokathor** [comment]
Sorry, I should have been more clear, this issue refers to `pub fn cmp_ord_mask_m128` as well as the [d] and [_s] variants, and also `pub fn cmp_unord_mask_m128` and variants.

**Comment by Lokathor** [comment]
So I guess my concerns are both the names themselves being not super helpful and also maybe the docs, though maybe just a clear name would work.

* `cmp_both_not_nan_mask_m128` is wordy but clear
* `cmp_either_is_nan_mask_m128` is similarly wordy but really gets the point across.
