### ISSUE TITLE
Ensure all macros have absolute `use` statements.

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/safe_arch#55]
All of the crate's macros should be written like `use ::core::arch::foo::bar;` (leading `::`) instead of just `use core::arch::foo::bar;`.

This should be a simple search and replace operation.

**Comment by Lokathor** [comment]
It seems that `rustfmt` is acting up and _removing_ the absolute prefixing on the use statement in the macros.

https://github.com/rust-lang/rustfmt/issues/4176

So I'm re-opening this until the rustfmt situation gets resolved.

**Comment by Soveu** [comment]
Is issue #36 also affected?

**Comment by Lokathor** [comment]
It was not.

However, I already heard back from the rustfmt people, and it's because the rustfmt.toml file didn't say `edition = "2018"` in it, which isn't a problem for `cargo fmt` because cargo sets it based on your crate's edition, but is a problem for individual `rustfmt` calls (which is what VS Code uses for "format on save") because rustfmt on its own doesn't know your edition.

So we're all set here.
